export const styles = {
  container: 'fixed inset-0 z-50 bg-black bg-opacity-85 px-lg',
  modalContent: 'flex h-full w-full flex-col items-center justify-center',
  header: 'absolute top-4 flex w-full items-center justify-center text-white',
  crossIcon: 'absolute right-[20px] top-0',
  navigation: 'absolute top-[49%] flex w-full items-center justify-between px-md text-white',
  image: 'max-w-screen max-h-[50%] object-contain mt-xxl',
  reviewContainer: 'mt-lg flex w-full flex-col text-white',
  reviewHeader: 'flex items-center text-white',
  avatarWrapper: 'ml-md text-light',
  separator: 'my-lg h-[1px] bg-white',
  reviewTitle: 'mb-sm text-text font-[600]',
  reviewText: 'overflow-hidden text-[14px] text-light',
  toggleButton: 'mt-2 text-[14px] font-bold text-primary',
  disabled: 'opacity-0',
  arrow: 'rotate-180 transform',
  userName: 'font-medium',
  providerName: 'text-light font-medium',
};
